version: '3.8'

services:
  app:
    image: ghcr.io/alex4108/converterd:latest
    container_name: converterd
    restart: always
    pull_policy: always
    environment:
      - WATCH_FOLDERS=/library
      - CHECK_SECONDS=60
      - LOG_LEVEL=INFO
    volumes:
      - /path/to/your/media/library:/library
    